<script>
   var datePickerOpt={
   showMonthAfterYear:false,
   dateFormat:"yy-mm-dd"
   };
</script>
<?php
$_PROJECT_NAME = "My Health";
$_LANGUAGE = "Language";
$_LOGIN = "Login";
$_USERNAME = "Username";
$_PASSWORD = "Password";
$_LOGIN_ERRORMSG = "Username or password error!";
$_SUBMIT = "Submit";
$_LOGOUT = "Logout";
$_WELCOME = "Welcome";
$_HEALTH_LOG = "Health Log";
$_HEALTH_CHARTS = "Health Charts";
$_USER_SETTING = "User Setting";
$_SYSTEM_SETTING = "System Setting";
$_ALL = "All";
$_ACCOUNT = "Account";
$_ITEM = "Item";
$_ARTICLE = "Article";
$_CATEGORY = "Category";
$_DEVICE = "Device";
$_MEASUREMENT = "Measurement";
$_MEASUREUNIT = "Measure Unit";
$_HIGH = "High";
$_LOW = "Low";
$_LIST_DATE = "List Date";
$_ADD = "Add";
$_EDIT = "Edit";
$_UPDATE = "Update";
$_DELETE = "Delete";
$_DELETE_MSG = "Are you sure to delete this?";
$_DATETIME = "Date/Time";
$_VALUE = "Value";
$_NOTES = "Notes";
$_ACTION = "Action";
$_NODATA_MSG = "No data found!";
$_MODE = "Mode";
$_USER_ARTICLE = "User Add ".$_ARTICLE."?";
$_NAME = "Name";
$_TYPE = "Type";
$_NONE = "None";
$_LOG_ENTRY = "Log Entry";
$_DATA_UPDATED = "Data Updated!";
$_TRACEING_ITEMS = "Tracing Items";
$_GENDER = "Gender";
$_MALE = "Male";
$_FEMALE = "Female";
$_YYYYMMDD = "(YYYY-MM-DD)";
$_BIRTHDAY = "Birthday";
$_EMAIL = "E-Mail";
$_PHONE = "Phone";
$_TIMEZONE = "Timezone";
$_TIMEZONE_TIP = "(ex. +8, in Taiwan)";
$_PASSWORD_CONFIRM = "Password Confirm";
$_WEIGHT_MEASUREMENT = "Weight Measurement";
$_GLUCOSE_MEASUREMENT =  "Glucose Measurement";
$_PWD_NOT_SAME = "Password not the same!";
$_PWD_REQUIRED = "Password is required!";
$_SYSTEM = "System";
$_USER = "User";
$_MODEL = "Model";
$_INFORMATION = "Information";
$_USERDEFINE = "User Define";
$_YES = "Yes";
$_NO = "No";
$_LIST = "List";
$_SELECT = "Select";
$_MINVAL = "Min. Value";
$_MAXVAL = "Max. Value";
$_LEVEL1 = "Level 1 Value";
$_LEVEL2 = "Level 2 Value";
$_SERIALNO = "Serial No.";
$_AUTHORITY = "Authority";
$_RECORDS = "Records";
$_DISABLED = "Disabled";
$_DISPLAY_ORDER = "Display Order";
$_DECIMAL = "Decimal";

?>
