<script>
   var datePickerOpt={
   dayNames:["星期日","星期一","星期二","星期三","星期四","星期五","星期六"],
   dayNamesMin:["日","一","二","三","四","五","六"],
   monthNames:["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
   monthNamesShort:["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
   prevText:"上月",
   nextText:"次月",
   weekHeader:"週",
   showMonthAfterYear:true,
   dateFormat:"yy-mm-dd"
   };
</script>
<?php
$_PROJECT_NAME = "我的健康站";
$_LANGUAGE = "使用語言";
$_LOGIN = "登入";
$_USERNAME = "帳號";
$_PASSWORD = "密碼";
$_LOGIN_ERRORMSG = "帳號或密碼錯誤!";
$_SUBMIT = "送出";
$_LOGOUT = "登出";
$_WELCOME = "歡迎";
$_HEALTH_LOG = "健康紀錄";
$_HEALTH_CHARTS = "健康圖表";
$_USER_SETTING = "個人設定";
$_SYSTEM_SETTING = "系統設定";
$_ALL = "全部";
$_ACCOUNT = "帳戶";
$_ITEM = "健康項目";
$_ARTICLE = "記錄細目";
$_CATEGORY = "紀錄分類";
$_DEVICE = "健康設備";
$_MEASUREMENT = "測量數值";
$_MEASUREUNIT = "測量單位";
$_HIGH = "高值";
$_LOW = "低值";
$_LIST_DATE = "日期期間";
$_ADD = "新增";
$_EDIT = "編輯";
$_UPDATE = "更新";
$_DELETE = "刪除";
$_DELETE_MSG = "你確定要刪除嗎?";
$_DATETIME = "日期/時間";
$_VALUE = "數值";
$_NOTES = "備註";
$_ACTION = "命令";
$_NODATA_MSG = "沒有符合條件的資料!";
$_MODE = "模式";
$_USER_ARTICLE = "是否可建".$_ARTICLE."?";
$_NAME = "名稱";
$_TYPE = "型態";
$_NONE = "無";
$_LOG_ENTRY = "登錄紀錄";
$_DATA_UPDATED = "資料已更新!";
$_TRACEING_ITEMS = "追蹤項目";
$_GENDER = "性別";
$_MALE = "男性";
$_FEMALE = "女性";
$_YYYYMMDD = "(西元年-月-日)";
$_BIRTHDAY = "生日";
$_EMAIL = "電子信箱";
$_PHONE = "聯絡電話";
$_TIMEZONE = "時區";
$_TIMEZONE_TIP = "(例如:+8, 臺灣時區)";
$_PASSWORD_CONFIRM = "密碼再次確認";
$_WEIGHT_MEASUREMENT = "體重單位";
$_GLUCOSE_MEASUREMENT =  "血糖單位";
$_PWD_NOT_SAME = "兩組密碼不相同!";
$_PWD_REQUIRED = "密碼必須設定!";
$_SYSTEM = "系統設定";
$_USER = "個人設定";
$_MODEL = "型號";
$_INFORMATION = "詳細資料";
$_USERDEFINE = "個人定義";
$_YES = "是";
$_NO = "否";
$_LIST = "條列式";
$_SELECT = "選項式";
$_MINVAL = "最小參考值";
$_MAXVAL = "最大參考值";
$_LEVEL1 = "第一界值";
$_LEVEL2 = "第二界值";
$_SERIALNO = "設備序號";
$_AUTHORITY = "權限";
$_RECORDS = "筆數";
$_DISABLED = "失效";
$_DISPLAY_ORDER = "顯示序";
$_DECIMAL = "小數點";

?>
